### ISSUE TITLE
Readme will be out of date soon as codehous.org is removing hosting services

### ISSUE THREAD

**Issue by AndrewLngdn** [square/jetpack#53]
In the readme, the jetty looks like this:
    jetty: "http://dist.codehaus.org/jetty/jetty-hightide-8.1.16/jetty-hightide-8.1.16.v20140903.zip"

codehous.org is suspending services this month, so this link will be out of date

**Comment by cheister** [comment]
Fixed with https://github.com/square/jetpack/pull/52
